image:
  repository: laimison/velero-backup-notification
  tag: 0.1

slack:
  enabled: false
  webhook: "https://...."
  channel: "stuff"
  username: Velero

email:
  enabled: true
  smtp:
    host: some-smtp-host.com
    port: 587
    username: blah
    password: blah
  from_address: from@email.com
  to_address: to@email.com
  subject_prefix: "[Velero]"
  from_sender_name: "Company X"

velero_namespace: velero
